version: '3.8'
services:
  dev:
    container_name: api_parking_lot
    image: api-parking-lot-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8888:8888
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always

networks:
  nesjs-network:
    driver: bridge
